### ISSUE TITLE
Decide on image for deterministic build dockerfile

### ISSUE THREAD

**Issue by Neotamandua** [dusk-network/dev-tools#4]
#### Summary

Currently the dockerfile uses ubuntu:24.04 and not rust as an image. We should gather information and make a decision as to which image (considering more than the two mentioned) would be best for this use case.

**Comment by HDauven** [comment]
We'll stick with Ubuntu:24.04 and explicitly make use of the Rust image being downloaded through rustup. Relying on the default Rust images, that are based on Debian, cause issues due to a Glibc mismatch.

As long as everything is very explicitly versioned, it's fine as is. We should also version the dockerfiles in some form and publish them.
